services:
  - type: web
    name: job-updates
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.9.0
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: MONGODB_URI
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHANNEL_ID
        sync: false
      - key: WHATSAPP_GATEWAY_URL
        sync: false
      - key: WHATSAPP_TOKEN
        sync: false
      - key: WHATSAPP_CHANNEL_ID
        sync: false
      - key: CRON_SECRET
        sync: false
      - key: ADMIN_USER
        value: admin
      - key: ADMIN_PASS
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false
      - key: NEXTAUTH_URL
        fromService:
          name: job-updates
          type: web
          property: host
